### ISSUE TITLE
MultiProvider doesn't fallback with KMS if access denied or wrong credentials provided

### ISSUE THREAD

**Issue by ggonchar** [awslabs/aws-encryption-sdk-java#4]
MultiProvider with KMS doesn't fallback to another key in the following scenarios:

1. Key exists but no permissions to access it. Exception:

> User: XXX is not authorized to perform: kms:GenerateDataKey on resource:XXX (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: XXX)
com.amazonaws.AmazonServiceException: User: XXX is not authorized to perform: kms:GenerateDataKey on resource: XXX (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: XXX)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1383)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:2497)
	at com.amazonaws.services.kms.AWSKMSClient.generateDataKey(AWSKMSClient.java:1347)
	at com.amazonaws.encryptionsdk.kms.KmsMasterKey.generateDataKey(KmsMasterKey.java:95)
	at com.amazonaws.encryptionsdk.internal.EncryptionHandler.<init>(EncryptionHandler.java:130)
	at com.amazonaws.encryptionsdk.AwsCrypto.encryptData(AwsCrypto.java:185)
	at com.amazonaws.encryptionsdk.AwsCrypto.encryptData(AwsCrypto.java:201)
	at AWSKeyEncryptionService.doEncrypt(EncryptionService.scala:64)
	at EncryptionServiceLoggingSupport$class.encrypt(EncryptionService.scala:78)
	at AWSKeyEncryptionService.encrypt(EncryptionService.scala:43)
	at AWSKeyEncryptionServiceIT$$anonfun$1.apply$mcV$sp(AWSKeyEncryptionServiceIT.scala:17)
	at AWSKeyEncryptionServiceIT$$anonfun$1.apply(AWSKeyEncryptionServiceIT.scala:14)
	at AWSKeyEncryptionServiceIT$$anonfun$1.apply(AWSKeyEncryptionServiceIT.scala:14)

2. Wrong secret key provided. Exception:

> ...
com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
...
	at com.amazonaws.encryptionsdk.kms.KmsMasterKey.encryptDataKey(KmsMasterKey.java:149)

**Comment by ggonchar** [comment]
Actually it should not do failover on encryption, but should do on decryption. My fault
